### ISSUE TITLE
File is not acessible: /home/hp/arg_work/test/mgs2amr-2.0.1-beta/dataAndScripts/bact.txids

### ISSUE THREAD

**Issue by quyho0944** [pieterjanvc/mgs2amr#10]
when i runned code in my project, i have problem 
BLAST query/options error: File is not acessible: /home/hp/arg_work/test/mgs2amr-2.0.1-beta/dataAndScripts/bact.txids
Please refer to the BLAST+ user manual.
and i don't know where this file is ?
if you have any solution of know where it is, please let me know

**Comment by pieterjanvc** [comment]
Hello

Did you make sure to install the pipeline using the [release](https://github.com/pieterjanvc/mgs2amr/releases/latest)? As stated in the README, the GitHub code itself only tracks important code files and not additional files needed to run the pipeline. They are all packages in the release.

Thanks
