### ISSUE TITLE
where is bactGenomeSize.csv

### ISSUE THREAD

**Issue by quyho0944** [pieterjanvc/mgs2amr#11]
when i tried to run this pipeline, in **step 4 annotation**, i got an error like this:
 ```
n file(file, "rt") :
  cannot open file ''/home/hp/arg_work/test/mgs2amr-2.0.1-beta/dataAndScripts/bactGenomeSize.csv'': No such file or directory
```
after that i find the line make error in line **56,57** file **ARG_annotation.R**:
```
bactGenomeSize = 
  read.csv(sprintf("%sdataAndScripts/bactGenomeSize.csv",baseFolder))
```
and i want to know where this file come from? if you have any solution for that please let me know, it will help me a lot.

**Comment by pieterjanvc** [comment]
Please see #10
