### ISSUE TITLE
 problem in Stage four (annotation) 

### ISSUE THREAD

**Issue by shaodongyan** [pieterjanvc/mgs2amr#4]
Last Error is:
 
Error in { : task 1 failed - "ℹ In argument: `startGroup = 1:n()`.
Caused by error:
! `startGroup` must be size 0 or 1, not 2."
Calls: %do% -> 
In addition: Warning message:
Specifying the `id_cols` argument by position was deprecated in tidyr 1.3.0.
ℹ Please explicitly name `id_cols`, like `id_cols = id`.
ℹ The deprecated feature was likely used in the gfaTools package.
 Please report the issue to the authors. 
Execution halted
 
What Should I do?  I’m looking forward to your reply! Thanks!!!!!!!!!!!!!!!!!!

**Comment by shaodongyan** [comment]
Hello PJ, I hope this message finds you well. I understand you may be busy, but I was wondering if you had a chance to look into the error I mentioned about the mgs2amr software. Any assistance or guidance you can provide would be greatly appreciated. Thank you for your time and consideration. @pieterjanvc

**Comment by shaodongyan** [comment]
I find the reason is blastSegments.csv 's start col is NA, But I don't know why . "name","sequence","LN","KC","group","geneId","start","blastId"
"730_2427","CGACCCCAACAACACCGGGTGTCGCCAGGGCCGTAGCCTGGGTGGTGACGCCTGGTGTGAAAAAATGGTAAGGGGAGAGCGGTGATTCCAATAGAACGACATCAGCGTATTTTAGCCCTGGTGGAGCAGCGTGGGGCGGTAAGCATTAACGAGCTGACGGAGATCCTCGGCGTGTCCCATATGACCATCCGTCGGGACGTCAGTAAACTGGAGGAGCAGGGGCTGCTGGTCAGCGTCTCGGGCGGCGTACGCGCCGTCAGCCGGCTGGCCGCGGAACCCAGTCATCTGGTGAAAAGCACGCTGCAGAGTGAGGAGAAACAGGCGATCGGCGCGCTGGCGGCGAGTCATATCGCTAAAAACAGTTGCATCTATCTGGATGCCGGGACTACCACCCTGGCGCTGGCGCGGGCGATCCTCGACCGGAACGATCTCCAGGTGGTCACCAATGATTTTGAGATAACCCAGCTGCTGATCGATGCCAGTCAGTGCGGCGTGATCCACACCGGCGGCACTCTGTGCCGGGAGAACCGCTCCTGCGTGGGCGAATCGGCGGCGCGTACGTTACGCCACCTGGCTATCGATACGGCCTTTATCTCCGCCAGCGGCTGGGACAGTCGCGGGATATTCACCCCTGATGAGAACAAGGTTACCGTCAAGGAGACCGTCAGCCAGGTCAGCGCGAGAAGCATCCTGCTGTGCGACAGTTCGAAATACAATCAGGTGGCCACGTTTATGGCGTTACCTTTGACCCGGTTCACCACCATCATTACCGACCGGCATCTCTCCGATGCCGCCGCCAGTCATATCGCCCGGCACGCCTGCGAGGTGCTACGAGCCGGATAACGCGCGCGGCCACCGCCGGGTTAGCGTTGCCAGTGCTCGATCAGCGCCGCGCCGATCCCGGCGATTTGCTGATTTCGCTCGGCCATGCTCGCCGGCGTATCCCGCAGATAAATCACCACAATCCGCTCTGCTTTGTTATTCGGGCCAAGCAGGGCGACAATCCCGCGCGCACCCCGTTTGCTAGCTCCGGTCTTATCGGCGATAAACCAGCCCGCCGGCAGCACGGAGCGGATCAACGGTCCGGCGACCCGATCGTCCACCATCCACTGCAGCAGCTGCCGTTGCGAACGGGCGCTCAGACGCTGGCTGGTCAGCAGCTTGCGCAGGGTCGCGGCCATGCTGGCCGGGGTAGTGGTGTCGCGGGCGTCGCCGGGAAGCGCCTCATTCAGTTCCGTTTCCCAGCGGTCAAGGCGGGTGACGTTGTCGCCGATCTGGCGCAAAAAGGCAGTCAATCCTGCGGGGCCGCCGACGGTGGCGCCGCCGCCATTACCATGAGCGATAACAGCGCCGCCAATCTGCTGCTGACAGAGTTCGCCGACCGTCATGCCGTCGGCA",1398,47633,201,"730",NA,"730_2427"


@pieterjanvc   can you help me?

**Comment by shaodongyan** [comment]
Sorry，but could you help me ? @pieterjanvc

**Comment by shaodongyan** [comment]
Hello PJ, I hope this message finds you well. I understand you may be busy, but I was wondering if you had a chance to look into the error I mentioned about the mgs2amr software. Any assistance or guidance you can provide would be greatly appreciated. Thank you for your time and consideration. @pieterjanvc

**Comment by shaodongyan** [comment]
Hello PJ,
I hope this message finds you well. I understand you may be busy, but I was wondering if you had a chance to look into the error I mentioned about the mgs2amr software. Any assistance or guidance you can provide would be greatly appreciated. I have been waiting for a response for two months now, and I would appreciate it if you could provide an update on the issue. Thank you for your time and consideration.
@pieterjanvc

**Comment by pieterjanvc** [comment]
Hello,

Sorry for the late reply. I will try and look into you issue in the coming week and get back at you. Can you let me know if this issue is happening with all data or just a specific set? 

Kind regards

**Comment by shaodongyan** [comment]
> Hello,
> 
> Sorry for the late reply. I will try and look into you issue in the coming week and get back at you. Can you let me know if this issue is happening with all data or just a specific set?
> 
> Kind regards

Thanks, this issue is happening with all data

**Comment by pieterjanvc** [comment]
Hello,

I think I might have fixed the issue. On your local machine, can you replace the files [dataAndScripts/ARG_annotation.R](https://github.com/pieterjanvc/mgs2amr/blob/4-problem-in-stage-four-annotation/dataAndScripts/ARG_annotation.R) and [dataAndScripts/blastPrep.R](https://github.com/pieterjanvc/mgs2amr/blob/4-problem-in-stage-four-annotation/dataAndScripts/blastPrep.R) with the updated versions from the [4-problem-in-stage-four-annotation](https://github.com/pieterjanvc/mgs2amr/tree/4-problem-in-stage-four-annotation/dataAndScripts) branch I created. (all other files should be the same).

You can then run your pipeline again. Please let me know if this helps

Thanks!

**Comment by shaodongyan** [comment]
> Hello,
> 
> I think I might have fixed the issue. On your local machine, can you replace the files [dataAndScripts/ARG_annotation.R](https://github.com/pieterjanvc/mgs2amr/blob/4-problem-in-stage-four-annotation/dataAndScripts/ARG_annotation.R) and [dataAndScripts/blastPrep.R](https://github.com/pieterjanvc/mgs2amr/blob/4-problem-in-stage-four-annotation/dataAndScripts/blastPrep.R) with the updated versions from the [4-problem-in-stage-four-annotation](https://github.com/pieterjanvc/mgs2amr/tree/4-problem-in-stage-four-annotation/dataAndScripts) branch I created. (all other files should be the same).
> 
> You can then run your pipeline again. Please let me know if this helps
> 
> Thanks!

I replace the R files and tested on test data. It make senses! Thanks
