### ISSUE TITLE
 Metacherchant Dependency Issue

### ISSUE THREAD

**Issue by HoangSon710** [pieterjanvc/mgs2amr#5]
Dear Dr. Pieter-Jan Van Camp,

I am writing to seek your guidance regarding an issue I encountered while trying to run the MGS2AMR pipeline described in your article "MGS2AMR: a gene-centric mining of metagenomic sequencing data for pathogens and their antimicrobial resistance profile."

During the process of building the environment, I received an error message stating that a Metacherchant dependent package was not recognized. I would greatly appreciate any insights or troubleshooting steps you could provide to resolve this problem. 

Thank you for your time and consideration. I am looking forward to hearing from you soon.

Son Hoang
![image](https://github.com/pieterjanvc/mgs2amr/assets/89684180/afd8667b-cffd-437d-ba88-7bed3ca0d254)
![image](https://github.com/pieterjanvc/mgs2amr/assets/89684180/1c26c3fd-1a1d-47ff-9e15-0b0b4ba6d431)
![image](https://github.com/pieterjanvc/mgs2amr/assets/89684180/f72d9ac2-4566-41d2-9d31-5ab368f09c06)

**Comment by shaodongyan** [comment]
Metacherchant in mgs2amr's tools folder

**Comment by pieterjanvc** [comment]
Hello,

I recently made a few bug fixes and I would recommend you to use the [latest release](https://github.com/pieterjanvc/mgs2amr/releases/latest) to ensure you have the most recent version of the pipeline.

Thanks
