### ISSUE TITLE
Issue at step 2 Blastn Prep 

### ISSUE THREAD

**Issue by nguyenwang2602** [pieterjanvc/mgs2amr#8]
![Screenshot from 2024-02-24 11-19-08](https://github.com/pieterjanvc/mgs2amr/assets/147074505/ecc40c55-cc29-4931-a237-c51222f3d23c)
while I'm running this step 2, this isue occurs seem to be can not move forward anymore. I would like some of your advices at this step!

**Comment by pieterjanvc** [comment]
Hello,

Does this issue happen with all datasets? (e.g. the test one provided in dataAndScripts/testData/testOutput.fastq.gz). If not, would you be able to provide me some more details about this specific dataset or upload the output folder as a zip file together with the mgs2amr.db file.

Thanks

**Comment by nguyenwang2602** [comment]
![Screenshot from 2024-03-05 08-55-06](https://github.com/pieterjanvc/mgs2amr/assets/147074505/b3d83439-0020-41cb-82b8-07bf8d3e26c3)
![Screenshot from 2024-03-05 08-57-01](https://github.com/pieterjanvc/mgs2amr/assets/147074505/ff60b49b-9391-456b-9a62-f75daf88a387)
It does not happen to all datasets, I tried this dataset from ARGref from 5800 ARG from the tables. Seem to be it has a problem in the script i ran? 
Hopefully can hear the answer from you soon!

**Comment by pieterjanvc** [comment]
Hello,

I'm a bit confused here. You seem to want to use a FASTA file as input, whereas this pipeline expects a FASTQ (zipped .gz) file. 

To be clear, the ARG 5800 genes checked in the pipeline cannot be changed unfortunately (this might be a future feature). So you input a metagenomic sequencing file (fastq.gz) and the pipeline will check it for all ARG found in the mgs2amr/dataAndScripts/ARG.fasta file and then try to annotate with any of the species detected.

Hope this helps

**Comment by nguyenwang2602** [comment]
Thank you sir, i'll be double check it again!!

**Comment by nguyenwang2602** [comment]
Sorry sir, i have already try it in fastq file as input and as you can see the pipeline could not run with it as this picture here 
![Screenshot from 2024-04-06 10-51-55](https://github.com/pieterjanvc/mgs2amr/assets/147074505/724e8529-9b4b-4265-8fc2-4f50d199070f)
and i want to fix the red error line. Really looking forward for your anwsers!!!
![Screenshot from 2024-04-06 10-53-49](https://github.com/pieterjanvc/mgs2amr/assets/147074505/9e3d1a3b-7016-4981-9c25-b31d58b13e31)

**Comment by pieterjanvc** [comment]
Hello again,

I'm still confused why you are using a FASTA files as input to the pipeline. Is [this](https://www.ncbi.nlm.nih.gov/nuccore/NG_074760.1/) the file you are using (I looked it up on NCBI)? If that's the case I you cannot use this as it is a specific resistance gene and not the sequencing data from an experiment.

If this is not the case, could you please share the input file you are using so I can download it an look at that specific case myself. You can share a link to it here if it's public data, or upload it to a cloud folder and share the link. 

Kind regards

**Comment by nguyenwang2602** [comment]
Sorry about that sir i made the wrong input. I'll replace it with fastq file again and maybe I'm misunderstood somewhere and I'll double check it again!
Thank for you reply!!!!
